### ISSUE TITLE
"gpr_tools -i GOPR0020.GPR -o GOPR0020.JPG -r 1:1" failed

### ISSUE THREAD

**Issue by supertobi** [gopro/gpr#2]
The command "gpr_tools -i GOPR0020.GPR -o GOPR0020.JPG -r 1:1" failed:

```
$ ./gpr_tools -i GOPR0020.GPR -o GOPR0020.JPG -r 1:1
[    0-ms]  GPR Tools Version 1.0.0 [master @ af95987] [Linux][GCC 7.3.0][64 bit] 
[    0-ms]  Input File: GOPR0020.GPR 
[    0-ms]  Output File: GOPR0020.JPG 
[   12-ms] [BEG] gpr_convert_gpr_to_rgb() /home/tobias/dev/gpr/source/lib/gpr_sdk/private/gpr.cpp (line 1695)
Could not decode input vc5 bitstream. Error number 20
gpr_tools: /home/tobias/dev/gpr/source/lib/gpr_sdk/private/gpr.cpp:1735: bool gpr_convert_gpr_to_rgb(const gpr_allocator*, GPR_RGB_RESOLUTION, int, gpr_buffer*, gpr_rgb_buffer*): Assertion `0' failed.
```

**Comment by supertobi** [comment]
And I have the same problem with "./gpr_tools -i GOPR0020.GPR -o GOPR0020.PPM -r 1:1 -b 16".

**Comment by adeelabbas** [comment]
1:1 mode is not supported yet. Please try 1:2 through 1:16

**Comment by dnewman-gpsw** [comment]
As this is intended as a VC5 RAW decoder to uncompressed RAW, a demosaic has not been included. This library and sample code was developed to help third integration into existing RAW tools.  That said, a simple GPR -> JPG/PPM at full resolution could be useful for applications beyond RAW photo tools.
