### ISSUE TITLE
table17.inc is copyrighted by Society of Motion Picture & Television Engineers LLC and Woodman Labs, Inc.

### ISSUE THREAD

**Issue by supertobi** [gopro/gpr#8]
gpr/source/lib/vc5_common/table17.inc

In the header of the file is this copyright note: 

	(c) 2013 Society of Motion Picture & Television Engineers LLC and Woodman Labs, Inc.
	All rights reserved--use subject to compliance with end user license agreement.

Is this compatible with the MIT/Apache license of the project? If yes, could you please change the header!

**Comment by dnewman-gpsw** [comment]
Fixed.  Sorry about that, SMPTE license the reference implementation, not used here.  However this .inc predates VC5, and it is from the CineForm SDK (also open under MIT/Apache licenses now https://github.com/gopro/cineform-sdk/blob/master/Common/table17.inc)

**Comment by supertobi** [comment]
Wow, thank, that was fast.
