### ISSUE TITLE
HERO7 sample missing

### ISSUE THREAD

**Issue by supertobi** [gopro/gpr#9]
It would be grate if you could add a HERO7 sample to "gpr/data/samples/".

**Comment by dnewman-gpsw** [comment]
Added a HERO7 GPR image.

**Comment by supertobi** [comment]
Btw: You/Gopro is absolutely welcomed to contribute to RPU (https://raw.pixls.us/).

**Comment by LebedevRI** [comment]
I have to echo what @supertobi said (though that is actually re-echo'ing myself now :D)
Lack of these samples on [RPU](https://raw.pixls.us/) **will** be limiting factor for https://github.com/darktable-org/rawspeed/pull/146

Not that you care/should care/have any obligation to do anything like that.

**Comment by dnewman-gpsw** [comment]
I just uploaded the sample I placed here to https://raw.pixls.us/.

**Comment by LebedevRI** [comment]
> I just uploaded the sample I placed here to https://raw.pixls.us/.

Thanks!
